on:
  pull_request:
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 main.py
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 main.py
